
interface _GlobalComponents {
      'IconsClose': typeof import("../components/Icons/Close.vue")['default']
    'IconsMenu': typeof import("../components/Icons/Menu.vue")['default']
    'IconsBehance': typeof import("../components/Icons/behance.vue")['default']
    'IconsBranding': typeof import("../components/Icons/branding.vue")['default']
    'IconsDesign': typeof import("../components/Icons/design.vue")['default']
    'IconsDiscord': typeof import("../components/Icons/discord.vue")['default']
    'IconsDownload': typeof import("../components/Icons/download.vue")['default']
    'IconsDribble': typeof import("../components/Icons/dribble.vue")['default']
    'IconsFigma': typeof import("../components/Icons/figma.vue")['default']
    'IconsGithub': typeof import("../components/Icons/github.vue")['default']
    'IconsGraphic': typeof import("../components/Icons/graphic.vue")['default']
    'IconsLinkedin': typeof import("../components/Icons/linkedin.vue")['default']
    'IconsLogo': typeof import("../components/Icons/logo.vue")['default']
    'IconsMotion': typeof import("../components/Icons/motion.vue")['default']
    'IconsSearch': typeof import("../components/Icons/search.vue")['default']
    'IconsSlack': typeof import("../components/Icons/slack.vue")['default']
    'IconsUser': typeof import("../components/Icons/user.vue")['default']
    'IconsYoutube': typeof import("../components/Icons/youtube.vue")['default']
    'Myfooter': typeof import("../components/Myfooter.vue")['default']
    'Mynav': typeof import("../components/Mynav.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyIconsClose': typeof import("../components/Icons/Close.vue")['default']
    'LazyIconsMenu': typeof import("../components/Icons/Menu.vue")['default']
    'LazyIconsBehance': typeof import("../components/Icons/behance.vue")['default']
    'LazyIconsBranding': typeof import("../components/Icons/branding.vue")['default']
    'LazyIconsDesign': typeof import("../components/Icons/design.vue")['default']
    'LazyIconsDiscord': typeof import("../components/Icons/discord.vue")['default']
    'LazyIconsDownload': typeof import("../components/Icons/download.vue")['default']
    'LazyIconsDribble': typeof import("../components/Icons/dribble.vue")['default']
    'LazyIconsFigma': typeof import("../components/Icons/figma.vue")['default']
    'LazyIconsGithub': typeof import("../components/Icons/github.vue")['default']
    'LazyIconsGraphic': typeof import("../components/Icons/graphic.vue")['default']
    'LazyIconsLinkedin': typeof import("../components/Icons/linkedin.vue")['default']
    'LazyIconsLogo': typeof import("../components/Icons/logo.vue")['default']
    'LazyIconsMotion': typeof import("../components/Icons/motion.vue")['default']
    'LazyIconsSearch': typeof import("../components/Icons/search.vue")['default']
    'LazyIconsSlack': typeof import("../components/Icons/slack.vue")['default']
    'LazyIconsUser': typeof import("../components/Icons/user.vue")['default']
    'LazyIconsYoutube': typeof import("../components/Icons/youtube.vue")['default']
    'LazyMyfooter': typeof import("../components/Myfooter.vue")['default']
    'LazyMynav': typeof import("../components/Mynav.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const IconsClose: typeof import("../components/Icons/Close.vue")['default']
export const IconsMenu: typeof import("../components/Icons/Menu.vue")['default']
export const IconsBehance: typeof import("../components/Icons/behance.vue")['default']
export const IconsBranding: typeof import("../components/Icons/branding.vue")['default']
export const IconsDesign: typeof import("../components/Icons/design.vue")['default']
export const IconsDiscord: typeof import("../components/Icons/discord.vue")['default']
export const IconsDownload: typeof import("../components/Icons/download.vue")['default']
export const IconsDribble: typeof import("../components/Icons/dribble.vue")['default']
export const IconsFigma: typeof import("../components/Icons/figma.vue")['default']
export const IconsGithub: typeof import("../components/Icons/github.vue")['default']
export const IconsGraphic: typeof import("../components/Icons/graphic.vue")['default']
export const IconsLinkedin: typeof import("../components/Icons/linkedin.vue")['default']
export const IconsLogo: typeof import("../components/Icons/logo.vue")['default']
export const IconsMotion: typeof import("../components/Icons/motion.vue")['default']
export const IconsSearch: typeof import("../components/Icons/search.vue")['default']
export const IconsSlack: typeof import("../components/Icons/slack.vue")['default']
export const IconsUser: typeof import("../components/Icons/user.vue")['default']
export const IconsYoutube: typeof import("../components/Icons/youtube.vue")['default']
export const Myfooter: typeof import("../components/Myfooter.vue")['default']
export const Mynav: typeof import("../components/Mynav.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyIconsClose: typeof import("../components/Icons/Close.vue")['default']
export const LazyIconsMenu: typeof import("../components/Icons/Menu.vue")['default']
export const LazyIconsBehance: typeof import("../components/Icons/behance.vue")['default']
export const LazyIconsBranding: typeof import("../components/Icons/branding.vue")['default']
export const LazyIconsDesign: typeof import("../components/Icons/design.vue")['default']
export const LazyIconsDiscord: typeof import("../components/Icons/discord.vue")['default']
export const LazyIconsDownload: typeof import("../components/Icons/download.vue")['default']
export const LazyIconsDribble: typeof import("../components/Icons/dribble.vue")['default']
export const LazyIconsFigma: typeof import("../components/Icons/figma.vue")['default']
export const LazyIconsGithub: typeof import("../components/Icons/github.vue")['default']
export const LazyIconsGraphic: typeof import("../components/Icons/graphic.vue")['default']
export const LazyIconsLinkedin: typeof import("../components/Icons/linkedin.vue")['default']
export const LazyIconsLogo: typeof import("../components/Icons/logo.vue")['default']
export const LazyIconsMotion: typeof import("../components/Icons/motion.vue")['default']
export const LazyIconsSearch: typeof import("../components/Icons/search.vue")['default']
export const LazyIconsSlack: typeof import("../components/Icons/slack.vue")['default']
export const LazyIconsUser: typeof import("../components/Icons/user.vue")['default']
export const LazyIconsYoutube: typeof import("../components/Icons/youtube.vue")['default']
export const LazyMyfooter: typeof import("../components/Myfooter.vue")['default']
export const LazyMynav: typeof import("../components/Mynav.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
