// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/1/2024, 3:41:09 PM
const configMerger = require("/home/ma_guy/Desktop/projects/github/ui-ux/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/ma_guy/Desktop/projects/github/ui-ux/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ma_guy/Desktop/projects/github/ui-ux/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ma_guy/Desktop/projects/github/ui-ux/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ma_guy/Desktop/projects/github/ui-ux/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ma_guy/Desktop/projects/github/ui-ux/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ma_guy/Desktop/projects/github/ui-ux/plugins/**/*.{js,ts,mjs}","/home/ma_guy/Desktop/projects/github/ui-ux/composables/**/*.{js,ts,mjs}","/home/ma_guy/Desktop/projects/github/ui-ux/utils/**/*.{js,ts,mjs}","/home/ma_guy/Desktop/projects/github/ui-ux/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/ma_guy/Desktop/projects/github/ui-ux/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/ma_guy/Desktop/projects/github/ui-ux/app.config.{js,ts,mjs}"] }));

module.exports = config
